version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly

    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Build
          command: |
            rustc --version
            cargo --version
            cargo build
      - save_cache:
          key: cache
          paths:
            - "~/.cargo"
            - "./target"

  lint_and_format:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Check code format
          command: |
            rustup component add rustfmt-preview
            rustfmt --version
            cargo fmt
  test:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          name: Run Test
          command: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint_and_format
      - test:
          requires:
            - build
